### ISSUE TITLE
Single Threaded Execution

### ISSUE THREAD

**Issue by ForgeMistress** [taskflow/taskflow#164]
I have a project I am upgrading Taskflow for and our graphics code requires it to be run on the main thread until we upgrade the API. Unfortunately, it doesn't look like I can pass ```0``` in as the number of threads to guarantee single-threaded execution anymore. Is there a way to do this or should I revert to the older version until we upgrade our graphics APIs to support multi-threaded draw calls?

**Comment by tsung-wei-huang** [comment]
Hi @ForgeMistress we do not support running the taskflow on main thread now, because of significant overhead in managing this special case. If you want a thread to run graphics, you may create an executor `tf::Executor executor(1)`. I know a lot of event/graphic libraries are single-threaded and it does take some time to upgrade those APIs to multithreading. So, to your question, yes, you may need to upgrade your graphics APIs to parallel versions.

**Comment by tsung-wei-huang** [comment]
The newest release doesn't intend to support this.
