### ISSUE TITLE
How to retrieve thread id?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [taskflow/taskflow#211]
Is there an equivalent of omp_get_thread_num()?
It is possible to get one from std::this_thread::get_id() of course but is there a way to get nicely numbered thread ids?
example: 0 .. N for 0.. N workers

**Comment by tsung-wei-huang** [comment]
@UNDEFINED-BEHAVIOR `executor.this_worker_id()`

**Comment by UNDEFINED-BEHAVIOR** [comment]
This is perfect, thank you!

**Comment by JoseAntFer** [comment]
Hello.

I had exactly this problem and I was about to discard taskflow just when I came about this answer. I want to point out that, as certainly you know, this feature can be very important to, for instance, avoid race conditions. I would like to suggest you to consider adding an small example of this in the github front page since I am sure many people looking to replace their OMP for-loops would be very happy to see it there.

Thank you very much for sharing such an amazing framework. Best regards,
José.
