### ISSUE TITLE
Method for managing task results to provide to the next task.

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#278]
We are currently using taskflow to support our robotic motion planning framework and one thing we are looking for is guidance on how best to pass the results of the preceding task to the next. We are currently looking at leveraging the tasks hash value for storing the results but for this to work the task needs to know which task resulted in the transition to lookup the results. Is it possible to know which was the previous task during execution? If not do you have guidance on how to manage task results when they are need by child tasks?

**Comment by Levi-Armstrong** [comment]
I have read through [this](https://github.com/taskflow/taskflow/issues/41) discussion.

**Comment by tsung-wei-huang** [comment]
Hi @Levi-Armstrong , this is indeed a design consideration in the very early stage of Taskflow. We do not support in-band data passing between tasks but ask users to manage data through their own data structures. The reason is as follows:

+ Data management is application-dependent. Indeed, task parallelism is more general than data parallelism.
+ It is very difficult to manage the data passing for multiple dependencies. For example, where to store the intermediate data is a big question for the framework.
+ I think data passing makes sense when it comes to pipeline, but not task graph parallelism.

So, the best way is to manage the data using client-side data structure. You will need to describe data dependencies through task dependencies.

**Comment by tsung-wei-huang** [comment]
I believe this issue can be solved by [attaching custom data to a task](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask), which will be included in the next release v3.3. 

Feel free to reopen this issue if necessary.

**Comment by Levi-Armstrong** [comment]
@tsung-wei-huang This is great!. I am curious why a C `void*` versus C++ variant `std::shared<void>`?

**Comment by Levi-Armstrong** [comment]
FYI @mpowelson and @marip8
