### ISSUE TITLE
why here do unlock?

### ISSUE THREAD

**Issue by sep19** [taskflow/taskflow#284]
https://github.com/taskflow/taskflow/blob/master/taskflow/utility/object_pool.hpp#L623

_gheap.mutex.unlock();

hello, why here do unlock, I can not understand

**Comment by tsung-wei-huang** [comment]
@sep19 , because [here](https://github.com/taskflow/taskflow/blob/33353d2b061eecc9e3671b78e2b8bb141128a6bc/taskflow/utility/object_pool.hpp#L603) locks the global heap to check if it has any superblock. If it is empty, we create a new one and this creation is irrelevant to the global heap, so we can free the lock.

**Comment by sep19** [comment]
thanks
