### ISSUE TITLE
Passing data from tasks to their successors

### ISSUE THREAD

**Issue by vkhomenko** [taskflow/taskflow#41]
Could you suggest an easy way to pass data (return values) from tasks to their successors?
Suppose A->C and B->C and C needs the results of A and B to proceed (typical of divide & conquer algorithms - BTW an example of d&q would be really helpful - e.g. TBB has a great example for recursive Fibonacci).

As far as I understand, I'd need to emplace A and B, getting the futures; then I need to capture the futures in a lambda that is passed to C.

Alternatively, I'd have to create variables for the results of A and B, and capture one of them in A and B, and both of them in C. This variables cannot be allocated on stack as it can get destroyed before the tasks have a chance to run, so one has to use dynamic memory allocation.

These approaches have major disadvantages:
  * futures are heavy objects, allocating memory and requiring synchronisation - I believe they are an overkill for this scenario: We already know that A and B have stopped once C is running, so it is safe to retrieve the return values without synchronisation; moreover, if A and B have not been destroyed yet (my understanding is that the clean-up is only performed when the graph terminates), no memory allocation is necessary.
  * The code becomes unnecessarily ugly - I think it would be much cleaner to pass a lambda accepting 2 parameters to C, and guarantee that the order of parameters corresponds to the order of precede() etc. calls.

**Comment by vkhomenko** [comment]
I've realised that the suggestion "to pass a lambda accepting 2 parameters to C, and guarantee that the order of parameters corresponds to the order of precede() etc. calls." is more complicated than it looks as the number of parameters is fixed at the compile time but the number of calls to precede() is not, and some of the preceding tasks may return void. Maybe you have some better ideas?

**Comment by twhuang-uiuc** [comment]
@vkhomenko Thanks for your comments! The bottom-most call to add dependencies between tasks is `precede` - all other methods such as `gather`, `linearize`, `broadcast`, etc are developed on top. So in most cases, you can decompose your applications to `precede` calls.

Passing data around tasks is still an open question in Taskflow. In my personal projects, I have been using lambda capture to share data among tasks. That is, each task actually gets a reference to the data it needs and the dependencies guarantee the data is correct when a task needs it. This actually works out very well. However, I do agree with your comment on how to make a control flow like *divide & conquer* more easier to write in Taskflow, since this type of pattern contains several temporary data that is difficult to capture in advance.

I am afraid the idea of using lambda arguments is not feasible because we use this for dynamic tasking - a task takes an argument on `subflow`. Maybe adding a member of type `std::any` to each task and makes it visible during the execution of a task? Well, `std::any` is kinda heavy too and it can only handles copy-coonstructible objects. Any thoughts?

**Comment by vkhomenko** [comment]
@twhuang-uiuc 
Thanks for the explanation. Still, precede() seems a low-level method, superseded by broadcast(). It can be retained as a private method, and not exposed to the user. This will simplify the interface without losing any expressive power / efficiency.

Concerning passing the return values to the successors: Could you confirm that if A->C and B->C then A and B are not destroyed when C is executing? If so, the return values can be stored in the functors passed to the tasks. It's easy to do if instead of a lambda one uses a proper class with operator() defined. Unfortunately, lambdas don't allow access to their data members (as far as I understand).

I still think using lambda arguments is the best approach - just overload on the type of the first argument - which is either a subflow builder or a different type (disable_if can be used to make sure it's not a subflow builder).

Sorry, these are just raw ideas...

**Comment by vkhomenko** [comment]
@twhuang-uiuc 

I've been thinking about something like:
```
auto A = tf.silent_emplace([] () { return 1; }); // no lambda arguments and so no predecessors
auto B = tf.silent_emplace([] () { return 1.2;}); // no lambda arguments and so no predecessors
auto C = tf.silent_emplace([] (int a, double b) { },A,B); // two arguments so there must be two predecessor tasks - so also creates two arcs in the graph; the return types should be convertible to the corresponding argument types

auto ANOTHER = tf.new_task([] () {}); // no lambda arguments and so no predecessors
D.precede(C); // interface for extra predecessors which don't return values
```

**Comment by fire** [comment]
Is it possible to use 
```
auto future = tf.dispatch();
```
to return the value?

future.get() is currently a void.

**Comment by clin99** [comment]
The `dispatch()` method is to return a future (handle) so that later you can check whether the graph execution is finished or not by calling `future.get()` instead of `wait_for_all`. If you wish to get a value which is generated during graph execution, one way I can think of is to create a `std::promise` and use the `future` from that promise to retrieve the value. 

For example:
```
tf::Taskflow tf;
std::promise<int> promise;
auto future = promise.get();
auto task = tf.silent_emplace(
   [&] () {
       // Do some calculation and set the result
       promise.set(calculate());
   }
);
tf.silent_dispatch();  
std::cout << "Result = " << future.get() << '\n';
```
 
This can also be done by just passing a reference to a variable into the task and store the result in that variable.

Thanks.

**Comment by markg85** [comment]
Hi,

I was just about to submit a request for this very feature when i saw this one.

Passing the result of an executed lambda to it's successor would be very nice!
That also makes this look a lot more like the javascript async/await principle imho.

**Comment by vkhomenko** [comment]
Futures are mentioned in the opening post - the problem is that futures require additional (unnecessary) synchronisation, memory allocation, and generally are heavy objects.

The problem with passing references is that one cannot get an address of a data member in a lambda, i.e. have to fall back to explicit classes.

**Comment by rebasamo** [comment]
Instead of using futures, there is a way of ensuring that the values you want are modified in the tasks.
Here is an example:
![image](https://user-images.githubusercontent.com/32878584/50050633-20e53c80-0101-11e9-94cf-6c1b5106ab21.png)

If you stay in scope before you call "wait_for_all" you are modifying the references and defining the order of the tasks the values will be correct when the functions are called.

I don't know if there is a way of using some sort of dynamic tuple so you can use the references from there and so, not have to worry about the scope.

Also I will use this post to make a suggestion.

Add: 
![image](https://user-images.githubusercontent.com/32878584/50050647-c1d3f780-0101-11e9-981b-62b06c2b5dac.png)

![image](https://user-images.githubusercontent.com/32878584/50050624-fabf9c80-0100-11e9-911d-2a21565b4a63.png)

That way you can send the function with the parameters instead of sending an std::bind(...).

**Comment by hrishikesh713** [comment]
> I am afraid the idea of using lambda arguments is not feasible because we use this for dynamic tasking - a task takes an argument on `subflow`. Maybe adding a member of type `std::any` to each task and makes it visible during the execution of a task? Well, `std::any` is kinda heavy too and it can only handles copy-coonstructible objects. Any thoughts?

@tsung-wei-huang how about using some third party libraries that implement [heterogeneous containers ](https://gieseanw.wordpress.com/2017/05/03/a-true-heterogeneous-container-in-c/) that employ copy-on-write strategies for efficient data movement across tasks. 
For example :
https://github.com/hosseinmoein/DataFrame
https://github.com/target/libdart

**Comment by Lecrapouille** [comment]
@hrishikesh713 concerning your link 'heterogeneous containers' since I used for my personal project, I have to warn you that the main issue with this implementation, as the author tell it, that this container acts as a unique container so all your data are stored in containers hold by a unique instance (static).

**Comment by Lecrapouille** [comment]
Here an idea: https://en.wikipedia.org/wiki/Kahn_process_networks

**Comment by tsung-wei-huang** [comment]
duplicate with #278 

(will keep track of this progress)
