### ISSUE TITLE
Prioritized Tasking for `tf::Taskflow`s

### ISSUE THREAD

**Issue by sunbubble** [taskflow/taskflow#433]
I just saw the upcoming [Prioritized Tasking](https://taskflow.github.io/taskflow/PrioritizedTasking.html) and I'm very happy to see it!
This is a question/feature request.

```C++
// setup ...

tf::Executor e;

e.run(taskflow_with_low_priority_tasks);
e.run(taskflow_with_high_priority_tasks);
```

Assuming there's no other order dependency, will the tasks from `taskflow_with_high_priority_tasks` be prioritised over the tasks of `taskflow_with_low_priority_tasks`?

**Comment by tsung-wei-huang** [comment]
Currently, priority is attached on a per-task basis, rather than taskflow. But you can always assign different priorities for tasks of different taskflows to control your behavior. 

The short answer to your last question is no - there is no guarantee that this priority will always work because the Taskflow runtime will automatically decide which task to run first or later for dynamic load balancing. But each worker will always try to steal/run the task with the highest priority first. If a steal is unsuccessful due to multiple steals, the worker will look for other tasks from the lower priority.

**Comment by sunbubble** [comment]
> The short answer to your last question is no - there is no guarantee that this priority will always work because the Taskflow runtime will automatically decide which task to run first or later for dynamic load balancing. But each worker will always try to steal/run the task with the highest priority first. If a steal is unsuccessful due to multiple steals, the worker will look for other tasks from the lower priority.

Sorry, I think I didn't express myself clearly. I meant prioritised on average, but without strict order guarantees.

> Currently, priority is attached on a per-task basis, rather than taskflow. But you can always assign different priorities for tasks of different taskflows to control your behavior.

From this, I understood that the answer is actually yes. But if you want a strict order of execution guarantee you must establish a precedence relation explicitly.

**Comment by tsung-wei-huang** [comment]
Close for now as there is no specific plan for implementing this feature.

**Comment by hyyou** [comment]
> priority is attached on a per-task basis

I can't find such feature.  I believe the cool per-task-priority feature is removed.
