### ISSUE TITLE
Does it able to run on old devices with only c++11 maxium support?

### ISSUE THREAD

**Issue by lucasjinreal** [taskflow/taskflow#471]
Does it able to run on old devices with only c++11 maxium support?

**Comment by tsung-wei-huang** [comment]
No - you will need c++17 to run Taskflow.

**Comment by jinfagang** [comment]
@tsung-wei-huang  thanks, I have 2 further questions:

1. how about build taskflow as static lib which using c++17, but deploy on enviroement only supports c++11?
2. Does run 2 onnx models parallel can have speed boost? I tried some other parallel framework, they actaully got slower then in sequential

**Comment by tsung-wei-huang** [comment]
1. I think this is actually quite difficult. Taskflow is header-only. To make a static library, you will need to link and expose the essential methods you need out of taskflow. But C++ has been historically regarded very difficult to build a static library...

2. Could you please be a bit more specific about what you mean by "run two onnx models parallels"? Do you want to create two tasks each run an inference instance of an ONNX model?

**Comment by jinfagang** [comment]
@tsung-wei-huang  Hi, simply run 2 onnx models at the same time, calculate the overall time, say timeB, run them one by one timeA, found timeB actually same or even slower than timeA.

This wasn't expected, since 2 models running in parallel, we should only oberve the slowerest time of them, but now it doesn't.

The 2 models are not running out GPU-mem at all, about 40% GPU-mem running togather, and GPU utils not up to 100%.

This is very weried.

**Comment by tsung-wei-huang** [comment]
I would say it may depend on how you run that on GPU. If you do a single stream, the 2 onnx models may still be serialized, even though you have two parallel tasks.

**Comment by tsung-wei-huang** [comment]
Close first - feel free to reopen with new activity.
