### ISSUE TITLE
Executor singleton

### ISSUE THREAD

**Issue by anderspitman** [taskflow/taskflow#475]
Hi @tsung-wei-huang,

My name is Anders. I'm a software engineer in the [Marth Lab](https://marthlab.org/) at the University of Utah. We primarily work on software tools for human genetics. One of our current projects is developing a library called [quickbam](https://gitlab.com/yiq/quickbam) to harness modern hardware and greatly accelerate IO performance for common genetics file operations, with the goal of decreasing turnaround times for genetic processing in time-sensitive clinical settings, such as pediatric cancer patients.

We're currently using oneTBB for our internal parallelization. However, this requires `libquickbam` to be dynamically linked, which can make development more difficult for our users. We're looking into providing a statically linked library, or possible even moving to header-only distribution.

When looking into statically linking TBB, I came across the following: https://stackoverflow.com/a/19684240/943814

which explains that it's a bad idea to statically link TBB.

Being header-only, I'm curious if Taskflow is susceptible to a similar scheduler sharing problem? For example, if we switched to using Taskflow for quickbam's internal parallelization, and one of our users also used Taskflow for their program, is there any way to share a single scheduler or coordinate between multiple schedulers so that scheduling is still efficient?

**Comment by tsung-wei-huang** [comment]
@anderspitman Thanks for your interest in Taskflow. I personally don't recommend statically linking TBB because it has included many platform-specific libraries. Yes, you are right. TBB has the problem of a globally shared thread resources to do the scheduling. This is a feature of TBB and can cause many global state sharing problems. 

In Taskflow, you will need to create an executor that does all threading in an object-oriented fashion. To be more precise, Taskflow does not have any global or even thread-local variables. You may give it a try and see if it can benefit your project. Since we are both in Utah, you can shoot me an [email](tsung-wei.huang@utah.edu) if you would like to understand more details :) Always open to collaborate.

**Comment by tsung-wei-huang** [comment]
Yes, all the `run` methods in executor are thread-safe. You can have multiple threads submitting different taskflows at the same time.

Yes, you will need to create a global executor yourself and potentially ask others to get your instance from your function (`quickbam::get_taskflow_executor()`)

**Comment by anderspitman** [comment]
Excellent, thank you!
