### ISSUE TITLE
Thread affinity of Pipes in the tf::Pipeflow 

### ISSUE THREAD

**Issue by antonysigma** [taskflow/taskflow#477]
Follow up question from #476 : does tf::Pipeflow guarantee thread affinity of the pipeline? In other words, if I coded the ReadPipe to store data to (L2/L3) cache in thead 1, does the ProcessPipe read the same data from thread 1 as well?

I am aware that the logical thread affinity is different from physical CPU core affinity, like what we do with the NUMA architecture. Agreed that CPU affinity requirement of out of the Taskflow project scope.

**Comment by tsung-wei-huang** [comment]
This is not guaranteed. The order of which worker executes which pipe is completely dynamic, decided by the runtime due to work-stealing. This of course has a significant benefit on load balancing but in some cases you may encounter cache miss more often. But in our experience, having a good load-balancing scheduler is much better.

**Comment by antonysigma** [comment]
Acknowledged. To paraphrase, although one worker executes the "tasks" of the pipe in one thread to avoid scheduling overhead (reference: #476 ), there's no guarantee the "logical" thread ties to the "physical" CPU core in practice. Cache miss can happen. The underlying OS ultimately controls the thread to CPU core affinity.

**Comment by tsung-wei-huang** [comment]
Yes, you are correct.
