### ISSUE TITLE
Ability to execute a function on setup for thread for an executor

### ISSUE THREAD

**Issue by IkeOTL** [taskflow/taskflow#641]
I have some thread_locals per thread that I want to setup as soon as I create the executor so I dont have to lazily initialize them.

I'm currently doing it like this, but it doesnt feel guaranteed to work?
```
tf::Taskflow taskflow;
auto num_threads = executor.num_workers();

taskflow.for_each_index(0, num_threads, 1, [onThreadStartup](int i) {
    KE_LOG_DEBUG(std::format("Initialized pool thread: {}", i));
    (*onThreadStartup)();
});

executor.run(taskflow).wait();
```

Is there a currently recommended way to do this?

**Comment by tsung-wei-huang** [comment]
The best way is to manage the thread-local data structure yourself and call `tf::Executor::this_worker_id` to get the index of the caller thread (`0` to `N-1` if the caller is a worker of the executor or `-1` otherwise).  Once you have the id, you can use it to update your thread-local data structure.

**Comment by IkeOTL** [comment]
Thanks, I'll try that out.
